"""empty message

Revision ID: ab7f60c58d1d
Revises: 77f00a72bf1d
Create Date: 2021-02-05 18:43:48.205211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7f60c58d1d'
down_revision = '77f00a72bf1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_column('post', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('post', 'post_id')
    # ### end Alembic commands ###
